### ISSUE TITLE
Rename search2bag createbag

### ISSUE THREAD

**Issue by rpwagner** [fair-research/concierge#2]
The term `search` doesn't have any context in the current Concierge services. Better to rename or alias the `search2bag` view to `createbag`.

**Comment by NickolausDS** [comment]
I'm curious where you found the `search` term. I looked through the repo and couldn't find it.

**Comment by rpwagner** [comment]
Ah, this could be a mistake on my part. I thought the URL for creating a bag was `/search2bag`. But since it's the Django REST Framework, it's `/bag`, isn't it?

**Comment by rpwagner** [comment]
Duh. In the readme: `https://example.com/api/bags/`

Never mind.
